// vue2-vite-routing-store-app/src/views/About.vue
<template>
  <div>
    <h3>About</h3>
    <p>This is a generic about page</p>
    <p>
      Bacon ipsum dolor amet shank turkey andouille prosciutto tenderloin
      chicken biltong fatback bacon swine sirloin chislic bresaola shankle
      frankfurter. Meatloaf biltong swine shankle. Buffalo turkey pig short
      ribs, frankfurter meatloaf cow pancetta. Turkey hamburger swine sausage
      sirloin. Short loin capicola ground round kielbasa pork. Chicken bacon
      pastrami picanha turkey. Sausage chislic pastrami hamburger, meatloaf
      bresaola porchetta brisket cupim.
    </p>
  </div>
</template>

// svelte-routing-store-app/src/routes/About.svelte
<h3>About</h3>
<p>This is a generic about page</p>
<p>
  Bacon ipsum dolor amet shank turkey andouille prosciutto tenderloin chicken
  biltong fatback bacon swine sirloin chislic bresaola shankle frankfurter.
  Meatloaf biltong swine shankle. Buffalo turkey pig short ribs, frankfurter
  meatloaf cow pancetta. Turkey hamburger swine sausage sirloin. Short loin
  capicola ground round kielbasa pork. Chicken bacon pastrami picanha turkey.
  Sausage chislic pastrami hamburger, meatloaf bresaola porchetta brisket cupim.
</p>
