// nuxt-app/components/Products/ProductItem.vue
<template>
  <div class="product">
    <p class="product-title">{{ title }}: €{{ price }}</p>
    <p>{{ info }}</p>
    <button @click="addToShoppingCart">Add to Shopping Cart</button>
  </div>
</template>

<script>
import { mapActions } from "vuex";
export default {
  props: {
    title: {
      type: String,
      default: '',
    },
    price: {
      type: Number,
      default: 0,
    },
    info: {
      type: String,
      default: '',
    },
    id: {
      type: String,
      default: '',
    },
  },
  methods: {
    ...mapActions("shoppingCartModule", ["addItemToShoppingCart"]),
    addToShoppingCart() {
      this.addItemToShoppingCart({
        id: this.id,
        title: this.title,
        price: this.price,
        info: this.info,
      });
    },
  },
};
</script>

<style>
.product {
  margin: 10px;
  border-radius: 10px;
  background: #f9eecb;
  box-shadow: rgba(0, 0, 0, 0.2) 0px 5px 15px;
  padding: 10px;
}

.product-title {
  font-weight: bold;
}
</style>

// svelte-kit-app/src/components/Products/ProductItem.svelte
<script>
  import shoppingCartItems from "../../stores/shopping-cart-store.js";

  export let id;
  export let title;
  export let price;
  export let info;

  function addToShoppingCart() {
    shoppingCartItems.addItemToShoppingCart({
      id,
      title,
      price,
      info,
    });
  }
</script>

<div class="product">
  <p class="product-title">{title}: €{price}</p>
  <p>{info}</p>
  <button on:click={addToShoppingCart}>Add to Shopping Cart</button>
</div>

<style>
  .product {
    margin: 10px;
    border-radius: 10px;
    background: #f9eecb;
    box-shadow: rgba(0, 0, 0, 0.2) 0px 5px 15px;
    padding: 10px;
  }

  .product-title {
    font-weight: bold;
  }
</style>
