// svelte-routing-store-app/src/App.svelte
<script lang="ts">
  import { Router, Route, Link } from "svelte-navigator";
  import Home from "./routes/Home.svelte";
  import Blog from "./routes/Blog.svelte";
  import About from "./routes/About.svelte";
</script>

<Router>
  <header>
    <nav>
      <Link to="/">Home</Link>
      <Link to="blog">Blog</Link>
      <Link to="about">About</Link>
    </nav>
  </header>

  <main>
    <Route>
      <Home />
    </Route>

    <Route path="blog/*blogRoute" component={Blog} />

    <Route path="about">
      <About />
    </Route>
  </main>
</Router>

<style>
  nav {
    background: #68cb80;
    font-size: 2rem;
    display: flex;
    justify-content: space-evenly;
  }
  main {
    text-align: center;
    padding: 1em;
    max-width: 240px;
    margin: 0 auto;
  }

  @media (min-width: 640px) {
    main {
      max-width: none;
    }
  }
</style>

// vue2-vite-routing-store-app/src/App.vue
<template>
  <div id="app">
    <header>
      <nav class="main-nav">
        <router-link to="/">Home</router-link>
        <router-link to="/blog">Blog</router-link>
        <router-link to="/about">About</router-link>
      </nav>
    </header>
    <main>
      <router-view></router-view>
    </main>
  </div>
</template>

<style>
@import '../src/assets/global.css';
main {
  text-align: center;
  padding: 1em;
  max-width: 240px;
  margin: 0 auto;
}

@media (min-width: 640px) {
  main {
    max-width: none;
  }
}
</style>
