// svelte-kit-app/src/routes/blog/index.svelte
<svelte:head>
  <title>Blog</title>
</svelte:head>

<div class="Blog">
  <h3>Blog</h3>

  <nav>
    <a href="../">Go back to the home page</a>
  </nav>

  <p>
    You can access nested routes like
    <a href="/blog/nested-route1">Nested route 1</a>
    or
    <a href="/blog/nested-route2">Nested route 2</a>
  </p>
</div>

// vue2-vite-routing-store-app/src/views/Blog.vue
<template>
  <div>
    <h3>Blog</h3>

    <nav>
       <router-link to="/">Go back to the home page</router-link>
    </nav>

    <p>
        You can access inner routes like
        <router-link to="/blog/nested-route1">Nested route 1</router-link>
        or
        <router-link to="/blog/nested-route2">Nested route 2</router-link>
    </p>
    <router-view></router-view>
  </div>
</template>
