// svelte-routing-store-app/src/routes/Home.svelte
<script>
  import Products from "../components/Products/Products.svelte";
  import ShoppingCart from "../components/ShoppingCart/ShoppingCart.svelte";
</script>

<h3>Home page</h3>
<p>Note: Any unknown route will end up here.</p>

<div class="container">
  <Products />
  <ShoppingCart />
</div>

<style>
  .container {
    display: flex;
  }
</style>

// vue2-vite-routing-store-app/src/views/Home.vue
<template>
  <div>
    <h3>Home page</h3>
    <p>Note: Any unknown route will end up here.</p>

    <div class="container">
      <products />
      <shopping-cart />
    </div>
  </div>
</template>

<script>
import Products from '../components/Products/Products.vue'
import ShoppingCart from '../components/ShoppingCart/ShoppingCart.vue'
export default {
  components: {
    Products,
    ShoppingCart,
  }
}
</script>
<style>
  .container {
    display: flex;
  }
</style>
