// svelte-kit-app/src/routes/blog/nested-route2.svelte
<nav>
  <a href="/blog">Go to Blog</a>
</nav>

<h3>Nested route 2</h3>
<p>
  Pork chop hamburger cow tail. Beef ground round boudin capicola short
  loin prosciutto brisket chuck biltong cupim pancetta strip steak
  picanha pig pork belly. Beef ribs turducken ham hock doner, cow
  tri-tip tongue jowl pork chop t-bone frankfurter. Corned beef meatloaf
  rump, bacon shoulder frankfurter pork chop pork loin turkey cupim
  sirloin sausage pig venison. Tri-tip t-bone meatball pork, strip steak
  meatloaf pastrami. Brisket tail shankle frankfurter strip steak
  kielbasa cupim filet mignon sausage. Fatback salami tail, boudin pig
  cow frankfurter alcatra meatball tenderloin picanha tri-tip.
</p>

// vue2-vite-routing-store-app/src/views/NestedRoute2.vue
<template>
  <div>
    <h3>Nested route 2</h3>
    <p>
      Pork chop hamburger cow tail. Beef ground round boudin capicola short loin
      prosciutto brisket chuck biltong cupim pancetta strip steak picanha pig
      pork belly. Beef ribs turducken ham hock doner, cow tri-tip tongue jowl
      pork chop t-bone frankfurter. Corned beef meatloaf rump, bacon shoulder
      frankfurter pork chop pork loin turkey cupim sirloin sausage pig venison.
      Tri-tip t-bone meatball pork, strip steak meatloaf pastrami. Brisket tail
      shankle frankfurter strip steak kielbasa cupim filet mignon sausage.
      Fatback salami tail, boudin pig cow frankfurter alcatra meatball
      tenderloin picanha tri-tip.
    </p>
  </div>
</template>
