// vue2-vite-routing-store-app/src/views/NestedRoute1.vue
<template>
  <div>
    <h3>Nested route 1</h3>
    <p>
      Strip steak tongue landjaeger meatloaf ham hock chuck ground round
      andouille spare ribs ribeye tenderloin meatball jowl leberkas. Fatback
      capicola meatloaf turkey kevin pork belly cow. Jowl short ribs beef ribs
      pancetta capicola cow chislic t-bone ham rump boudin. Sausage alcatra
      salami turducken spare ribs capicola, filet mignon bacon picanha pancetta
      chislic.
    </p>
  </div>
</template>

// svelte-kit-app/src/routes/blog/nested-route1.svelte
<nav>
  <a href="/blog">Go to Blog</a>
</nav>

<h3>Nested route 1</h3>
<p>
  Strip steak tongue landjaeger meatloaf ham hock chuck ground round
  andouille spare ribs ribeye tenderloin meatball jowl leberkas. Fatback
  capicola meatloaf turkey kevin pork belly cow. Jowl short ribs beef
  ribs pancetta capicola cow chislic t-bone ham rump boudin. Sausage
  alcatra salami turducken spare ribs capicola, filet mignon bacon
  picanha pancetta chislic.
</p>
