// svelte-routing-store-app/src/components/ShoppingCart/ShoppingCartItem.svelte
<script>
  import shoppingCartItems from "../ShoppingCart/shopping-cart-store.js";

  export let id;
  export let title;
  export let price;
  export let info;

  let showInfo = false;

  $: infoButtonLabel = showInfo ? "Less Info" : "More Info";

  function displayMoreInfo() {
    showInfo = !showInfo;
  }

  function removeFromShoppingCart() {
    shoppingCartItems.removeItemFromShoppingCart(id);
  }
</script>

<li>
  <p class="product-title">{title}: €{price}</p>
  <button on:click={displayMoreInfo}>{infoButtonLabel}</button>
  <button on:click={removeFromShoppingCart}>Remove Item</button>
  {#if showInfo}
    <p>{info}</p>
  {/if}
</li>

<style>
  li {
    margin: 10px;
    border-radius: 10px;
    background: #f9eecb;
    box-shadow: rgba(0, 0, 0, 0.2) 0px 5px 15px;
    padding: 10px;
  }

  .product-title {
    font-weight: bold;
  }
</style>

// nuxt-app/components/ShoppingCart/ShoppingCartItem.vue
<template>
  <li>
    <p class="product-title">{{ title }}: €{{ price }}</p>
    <button @click="displayMoreInfo">{{ infoButtonLabel }}</button>
    <button @click="removeFromShoppingCart">Remove Item</button>
    <p v-if="showInfo">{{ info }}</p>
  </li>
</template>

<script>
import { mapActions } from "vuex";
export default {
  props: {
    title: {
      type: String,
      default: '',
    },
    price: {
      type: Number,
      default: 0,
    },
    info: {
      type: String,
      default: '',
    },
    id: {
      type: String,
      default: '',
    },
  },
  data() {
    return {
      showInfo: false,
    };
  },
  computed: {
    infoButtonLabel() {
      return this.showInfo ? "Less Info" : "More Info";
    },
  },
  methods: {
    ...mapActions("shoppingCartModule", ["removeItemFromShoppingCart"]),
    displayMoreInfo() {
      this.showInfo = !this.showInfo;
    },
    removeFromShoppingCart() {
      this.removeItemFromShoppingCart(this.id);
    },
  },
};
</script>

<style>
li {
  margin: 10px;
  border-radius: 10px;
  background: #f9eecb;
  box-shadow: rgba(0, 0, 0, 0.2) 0px 5px 15px;
  padding: 10px;
}

.product-title {
  font-weight: bold;
}
</style>
