// svelte-kit-app/src/components/ShoppingCart/ShoppingCart.svelte
<script>
  import shoppingCartItems from "../../stores/shopping-cart-store.js";
  import ShoppingCartItem from "./ShoppingCartItem.svelte";

  let allItems;

  shoppingCartItems.subscribe((items) => {
    allItems = items;
  });
</script>

<section>
  <h1>Shopping Cart</h1>
  <ul>
    {#each allItems as item (item.id)}
      <ShoppingCartItem
        id={item.id}
        title={item.title}
        price={item.price}
        info={item.info} />
    {:else}
      <p>Shopping Cart is empty</p>
    {/each}
  </ul>
</section>

<style>
  section {
    width: 50%;
  }

  ul {
    list-style: none;
  }
</style>

// nuxt-app/components/ShoppingCart/ShoppingCart.vue
<template>
  <section>
    <h1>Shopping Cart</h1>
    <ul v-for="item in shoppingCartItems" :key="item.id">
      <shopping-cart-item
        :id="item.id"
        :title="item.title"
        :price="item.price"
        :info="item.info"
      />
    </ul>
    <p v-if="shoppingCartItems.length === 0">Shopping Cart is empty</p>
  </section>
</template>

<script>
import { mapState } from "vuex";
import ShoppingCartItem from "./ShoppingCartItem.vue";
export default {
  components: {
    ShoppingCartItem,
  },
  computed: {
    ...mapState("shoppingCartModule", ["shoppingCartItems"]),
  },
};
</script>

<style>
section {
  width: 50%;
}

ul {
  list-style: none;
}
</style>
