// svelte-kit-app/src/routes/blog/index.svelte
<svelte:head>
  <title>Blog</title>
</svelte:head>

<div class="Blog">
  <h3>Blog</h3>

  <nav>
    <a href="../">Go back to the home page</a>
  </nav>

  <p>
    You can access nested routes like
    <a href="/blog/nested-route1">Nested route 1</a>
    or
    <a href="/blog/nested-route2">Nested route 2</a>
  </p>
</div>

// nuxt-app/pages/blog/index.vue
<template>
  <div>
    <h3>Blog</h3>

    <nav>
       <NuxtLink to="/">Go back to the home page</NuxtLink>
    </nav>

    <p>
        You can access inner routes like
        <NuxtLink to="/blog/nestedRoute1">Nested route 1</NuxtLink>
        or
        <NuxtLink to="/blog/nestedRoute2">Nested route 2</NuxtLink>
    </p>
  </div>
</template>

<script>
export default {
  name: 'BlogPage',
}
</script>
